### ISSUE TITLE
2.17.2 upgrade to 3.0 crash

### ISSUE THREAD

**Issue by Yzc-jason** [Kentzo/ShortcutRecorder#104]
[General] An uncaught exception was raised
[General] Missing sr-mojave-info
 [General] (
	0   CoreFoundation                      0x00007fff4bde92fd __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff764dea17 objc_exception_throw + 48
	2   CoreFoundation                      0x00007fff4bde912f +[NSException raise:format:] + 201
	3   ShortcutRecorder                    0x000000010175c3c6 __53-[SRRecorderControlStyleResourceLoader infoForStyle:]_block_invoke.325 + 3014
	4   libsystem_trace.dylib               0x00007fff77ebe89c _os_activity_initiate_impl + 53
	5   ShortcutRecorder                    0x000000010175867b -[SRRecorderControlStyleResourceLoader infoForStyle:] + 2555
	6   ShortcutRecorder                    0x000000010175eb46 __63-[SRRecorderControlStyleResourceLoader lookupPrefixesForStyle:]_block_invoke + 2758
	7   libsystem_trace.dylib               0x00007fff77ebe89c _os_activity_initiate_impl + 53
	8   ShortcutRecorder                    0x000000010175dfe0 -[SRRecorderControlStyleResourceLoader lookupPrefixesForStyle:] + 288
	9   ShortcutRecorder                    0x000000010176613a -[SRRecorderControlStyle recorderControlAppearanceDidChange:] + 218
	10  ShortcutRecorder                    0x0000000101765c6a -[SRRecorderControlStyle prepareForRecorderControl:] + 570
	11  ShortcutRecorder                    0x00000001017434ed -[SRRecorderControl _setStyle:] + 509
	12  ShortcutRecorder                    0x00000001017431a4 -[SRRecorderControl style] + 116
	13  ShortcutRecorder                    0x0000000101742e63 -[SRRecorderControl setObjectValue:] + 787
	14  ShortcutRecorder                    0x0000000101743110 -[SRRecorderControl setValue:] + 128
	15  Foundation                          0x00007fff4dff1451 -[NSObject(NSKeyValueCoding) setValue:forKey:] + 331
	16  AppKit                              0x00007fff49426fcb -[NSObjectParameterBinder _updateObject:observedController:observedKeyPath:context:] + 1687
	17  AppKit                              0x00007fff493506be -[NSObject(NSKeyValueBindingCreation) bind:toObject:withKeyPath:options:] + 780
	18  vChat                               0x000000010005c7ee -[ShotCutSettingViewController configureView] + 158
	19  vChat                               0x000000010005c6af -[ShotCutSettingViewController viewDidLoad] + 79
	20  AppKit                              0x00007fff494adbaf -[NSViewController _sendViewDidLoad] + 94
	21  AppKit                              0x00007fff494aceb5 -[NSViewController _loadViewIfRequired] + 385
	22  AppKit                              0x00007fff494accea -[NSViewController view] + 30
	23  vChat                               0x00000001004f82ed -[RHPreferencesWindowController loadWindow] + 413
	24  AppKit                              0x00007fff49409f3e -[NSWindowController window] + 84
	25  AppKit                              0x00007fff495a417f -[NSWindowController showWindow:] + 36
	26  vChat                               0x0000000100201324 -[AppDelegate preferenceAction:] + 1508
	27  AppKit                              0x00007fff4961b644 -[NSApplication(NSResponder) sendAction:to:from:] + 312
	28  AppKit                              0x00007fff4967786b -[NSMenuItem _corePerformAction] + 323
	29  AppKit                              0x00007fff496775dc -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	30  AppKit                              0x00007fff496db58f -[NSMenu performActionForItemAtIndex:] + 131
	31  AppKit                              0x00007fff496db4fc -[NSMenu _internalPerformActionForItemAtIndex:] + 93
	32  AppKit                              0x00007fff496db32e -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 105
	33  AppKit                              0x00007fff49645dc6 NSSLMMenuEventHandler + 909
	34  HIToolbox                           0x00007fff4af8f22e _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1422
	35  HIToolbox                           0x00007fff4af8e5df _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 371
	36  HIToolbox                           0x00007fff4afab9b6 SendEventToEventTarget + 39
	37  HIToolbox                           0x00007fff4affdcd2 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 375
	38  HIToolbox                           0x00007fff4b02614e SendMenuCommandWithContextAndModifiers + 49
	39  HIToolbox                           0x00007fff4b0260fd SendMenuItemSelectedEvent + 192
	40  HIToolbox                           0x00007fff4b025fe5 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	41  HIToolbox                           0x00007fff4b0269b3 _ZL14MenuSelectCoreP8MenuData5PointdjPP13OpaqueMenuRefPt + 603
	42  HIToolbox                           0x00007fff4b0266c8 _HandleMenuSelection2 + 452
	43  AppKit                              0x00007fff49333aa1 _NSHandleCarbonMenuEvent + 223
	44  AppKit                              0x00007fff49333906 _DPSEventHandledByCarbon + 54
	45  AppKit                              0x00007fff4932894b -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 2577
	46  AppKit                              0x00007fff493225a8 -[NSApplication run] + 699
	47  AppKit                              0x00007fff49311ae8 NSApplicationMain + 777
	48  vChat                               0x00000001000601e2 main + 34
	49  libdyld.dylib                       0x00007fff77cac3d5 start + 1

**Comment by Kentzo** [comment]
It looks like either the file with resource was not bundled with the framework or somehow the framework failed to resolve the path.

Is it the current master? How was the framework added to the project?

**Comment by Yzc-jason** [comment]
yes,it is master. 
 2.17 : pod 'ShortcutRecorder/Core', :git => 'https://github.com/Kentzo/ShortcutRecorder', :branch => 'master'
3.0:  pod 'ShortcutRecorder' '~> 3.0'

**Comment by Kentzo** [comment]
Please try the develop branch.

**Comment by alanjslattery** [comment]
With the develop branch, the error is different, problem moves to SRLoc:

2019-09-27 11:01:17.624748+0100 Grabbit[7124:2841628] [General] Unable to find bundle with resources.
2019-09-27 11:01:17.633162+0100 Grabbit[7124:2841628] [General] (
	0   CoreFoundation                      0x00007fff46f33439 __exceptionPreprocess + 256
	1   libobjc.A.dylib                     0x00007fff716aa3c6 objc_exception_throw + 48
	2   ShortcutRecorder                    0x000000010041fa5a SRBundle + 186
	3   ShortcutRecorder                    0x000000010041fc4d SRLoc + 45
	4   ShortcutRecorder                    0x000000010043557a -[SRRecorderControl initInternalState] + 570
	5   ShortcutRecorder                    0x0000000100435316 -[SRRecorderControl initWithFrame:] + 150
	6   AppKit                              0x00007fff445366a8 -[NSView init] + 44
	7   Grabbit                             0x000000010001db03 $sSo17SRRecorderControlCABycfcTO + 19
	8   Grabbit                             0x000000010001cf3f $sSo17SRRecorderControlCABycfC + 31
	9   Grabbit                             0x000000010001d587 $s7Grabbit34ShortcutsPreferencesViewControllerC7nibName6bundleACSSSg_So8NSBundleCSgtcfc + 263
	10  Grabbit                             0x000000010001d78d $s7Grabbit34ShortcutsPreferencesViewControllerC7nibName6bundleACSSSg_So8NSBundleCSgtcfcTo + 173
	11  Grabbit                             0x000000010001bc83 $sSo16NSViewControllerCABycfcTO + 19
	12  Grabbit                             0x000000010000eeef $sSo16NSViewControllerCABycfC + 31
	13  Grabbit                             0x000000010000ed59 $s7Grabbit11AppDelegateC27preferencesWindowController11Preferences0geF0Cvg + 569
	14  Grabbit                             0x00000001000121ec $s7Grabbit11AppDelegateC21showPreferencesWindowyyypSgF + 60
	15  Grabbit                             0x000000010001231f $s7Grabbit11AppDelegateC21showPreferencesWindowyyypSgFTo + 175
	16  AppKit                              0x00007fff44757644 -[NSApplication(NSResponder) sendAction:to:from:] + 312
	17  AppKit                              0x00007fff447b386b -[NSMenuItem _corePerformAction] + 323
	18  AppKit                              0x00007fff447b35dc -[NSCarbonMenuImpl performActionWithHighlightingForItemAtIndex:] + 114
	19  AppKit                              0x00007fff4481758f -[NSMenu performActionForItemAtIndex:] + 131
	20  AppKit                              0x00007fff448174fc -[NSMenu _internalPerformActionForItemAtIndex:] + 93
	21  AppKit                              0x00007fff4481732e -[NSCarbonMenuImpl _carbonCommandProcessEvent:handlerCallRef:] + 105
	22  AppKit                              0x00007fff44781dc6 NSSLMMenuEventHandler + 909
	23  HIToolbox                           0x00007fff460cb22e _ZL23DispatchEventToHandlersP14EventTargetRecP14OpaqueEventRefP14HandlerCallRec + 1422
	24  HIToolbox                           0x00007fff460ca5df _ZL30SendEventToEventTargetInternalP14OpaqueEventRefP20OpaqueEventTargetRefP14HandlerCallRec + 371
	25  HIToolbox                           0x00007fff460e79b6 SendEventToEventTarget + 39
	26  HIToolbox                           0x00007fff46139cd2 _ZL18SendHICommandEventjPK9HICommandjjhPKvP20OpaqueEventTargetRefS5_PP14OpaqueEventRef + 375
	27  HIToolbox                           0x00007fff4616214e SendMenuCommandWithContextAndModifiers + 49
	28  HIToolbox                           0x00007fff461620fd SendMenuItemSelectedEvent + 192
	29  HIToolbox                           0x00007fff46161fe5 _ZL19FinishMenuSelectionP13SelectionDataP10MenuResultS2_ + 96
	30  HIToolbox                           0x00007fff46270cd1 _ZL19PopUpMenuSelectCoreP8MenuData5PointdS1_tjjPK4RecttjS4_S4_PK14__CFDictionaryPK10__CFStringPP13OpaqueMenuRefPt + 1601
	31  HIToolbox                           0x00007fff462701a9 _ZL26_HandlePopUpMenuSelection8P13OpaqueMenuRefP14OpaqueEventRefj5PointtjjPK4RecttS6_S6_PK14__CFDictionaryPK10__CFStringPS0_Pt + 418
	32  HIToolbox                           0x00007fff46142735 _HandlePopUpMenuSelectionWithDictionary + 329
	33  AppKit                              0x00007fff4480f66e _NSSLMPopUpCarbonMenu3 + 5496
	34  AppKit                              0x00007fff4480e050 -[NSCarbonMenuImpl popUpMenu:atLocation:width:forView:withSelectedItem:withFont:withFlags:withOptions:] + 439
	35  AppKit                              0x00007fff44c2b366 +[NSStatusBarButtonCell popupStatusBarMenu:inRect:ofView:withEvent:] + 1006
	36  AppKit                              0x00007fff44c2a539 -[NSStatusBarButtonCell trackMouse:inRect:ofView:untilMouseUp:] + 144
	37  AppKit                              0x00007fff447beb1e -[NSControl mouseDown:] + 791
	38  AppKit                              0x00007fff4469a937 -[NSWindow(NSEventRouting) _handleMouseDownEvent:isDelayedEvent:] + 5724
	39  AppKit                              0x00007fff445d11a6 -[NSWindow(NSEventRouting) _reallySendEvent:isDelayedEvent:] + 2295
	40  AppKit                              0x00007fff445d0667 -[NSWindow(NSEventRouting) sendEvent:] + 478
	41  AppKit                              0x00007fff44c2ceea -[NSStatusBarWindow sendEvent:] + 347
	42  AppKit                              0x00007fff4446fe6b -[NSApplication(NSEvent) sendEvent:] + 331
	43  AppKit                              0x00007fff4445e5e0 -[NSApplication run] + 755
	44  AppKit                              0x00007fff4444dae8 NSApplicationMain + 777
	45  Grabbit                             0x000000010001adbd main + 13
	46  libdyld.dylib                       0x00007fff72e6f3d5 start + 1

**Comment by Kentzo** [comment]
Please try again.

**Comment by Kentzo** [comment]
Thank you all for the reporting. 3.1 is released and the issue should be now addressed.
