### ISSUE TITLE
Warning About SRShortcutAction dispatchQueue

### ISSUE THREAD

**Issue by bdkjones** [Kentzo/ShortcutRecorder#121]
In Xcode 11.4 on macOS 10.15.4, I'm seeing the warning below about the `@property` declaration for the `dispatchQueue` in `SRShortcutAction.h`. It would be nice to resolve this. I don't really like using the `-w` flag to turn off warnings because then I miss things when I update the files.

Thanks!

![Screen Shot 2020-04-05 at 00 18 52](https://user-images.githubusercontent.com/926566/78469121-09094180-76d3-11ea-9fbe-079f18269c99.png)

**Comment by Kentzo** [comment]
Thank you for the report.

The dispatch queue will be gone in the next release.
