### ISSUE TITLE
Add support for the fn key as a modifier

### ISSUE THREAD

**Issue by lwouis** [Kentzo/ShortcutRecorder#132]
Hi @Kentzo!

A user [asked today](https://github.com/lwouis/alt-tab-macos/issues/661) why they can't bind the `fn` key in shortcuts. I never thought about that, but after thinking about it and looking at Apple docs, it seems like it's a valid idea.

I looked in SR's codebase and couldn't find any reference to [`kcgeventflagmasksecondaryfn`](https://developer.apple.com/documentation/coregraphics/cgeventflags/kcgeventflagmasksecondaryfn?language=objc). I couldn't find tickets talking about the `fn` key neither.

Is it explicitly not supported for a reason, or is it just that no-one wanted this so far?

**Comment by Kentzo** [comment]
Many external keyboards do not have the Fn button. The key in general is reserved to alter the touch bar and keyboard behavior.

It's likely that _certain_ shortcuts can be recorded with Fn but milage may vary depending on OS version, locale, system language, selected input source etc. I thus never added support for it to avoid support tickets in other products I maintain. IIRC public Carbon API that SR uses cannot handle Fn.

**Comment by lwouis** [comment]
I just tested the fn key on macOS built-on shortcuts in `System Preferences > Keyboard > Shortcuts`. It has a very weird behavior! When pressing `fn`-`D`, it registers the shortcut as such:

![image](https://user-images.githubusercontent.com/106195/97458268-e3e56480-197d-11eb-95a6-a4aa242f6169.png)

It doesn't show a symbol for the `fn` key. 2 things to note here:

* Pressing `D` alone doesn't trigger it
* Pressing `fn`-`D` does trigger it
* There is no way to record a shortcut without modifier in that UI, so pressing just `D` doesn't capture the shortcut. You have to add `alt`, `command`, or another modifier.

It seems then that macOS lets user use `fn` as any other modifier, but the UI is bugged and doesn't show the `fn` key.

I'll test if the Carbon APIs work with `fn` key, out of curiosity, but the reasoning you shared about "avoid support tickets in other products I maintain" makes a lot of sense. The scenario on my screenshot is a literal bug to me, and I could imagine a user going to Apple support saying "I'm pressing D and it doesn't trigger". Also as you mentioned `fn` can be bound to many things, and depends on a lot of context such as which generation of macbook, etc.

Thanks for you quick reply @Kentzo! 🙇‍♂️

**Comment by Kentzo** [comment]
The shortcut recorder control Apple uses in that pref pane is… far from being ideal. If only there was an alternative :)
