### ISSUE TITLE
Support for Apple Silicon?

### ISSUE THREAD

**Issue by lwouis** [Kentzo/ShortcutRecorder#134]
Hi @Kentzo,

Users of AltTab have been requested a Universal App, to have the app run natively on their Apple Silicon macs. For an app to run on ARM arch, it should have all its dependencies be compiled for ARM as well, as I understand it. This means AltTab would need a Universal Build of ShortcutRecorder.

Are there any plans to release a Universal Build of ShortcutRecorder to support the new Apple Silicon macs?

Thanks!

**Comment by Kentzo** [comment]
Have you tried integrating SR with SPM? It should support Apple Silicon without extra actions.

**Comment by lwouis** [comment]
Interesting. I've never tried SPM actually. I'll try to replace Cocoapods with it to see. I'm expecting lots of issues though, as these things are very complex 😅

Thanks for the very quick answer!

**Comment by Kentzo** [comment]
I currently have neither 11 nor Apple Silicon, so would be hard to debug Universal Builds. But it's definitely a thing to have.

**Comment by gcox** [comment]
@lwouis Most dependencies don't require any changes for Apple Silicon. I can confirm that ShortcutRecorder works fine on Apple Silicon and it doesn't matter whether you use CocoaPods or SPM to integrate it.

**Comment by lwouis** [comment]
@gcox all right, i'll close this ticket then now. Thanks everyone!
