### ISSUE TITLE
Split the protected interface of SRRecorderControl into a separate header?

### ISSUE THREAD

**Issue by zoul** [Kentzo/ShortcutRecorder#28]
The public interface of the `SRRecorderControl` class is quite big. And a good half of the methods are not intented for public consumption – some of them could be used by subclasses, some should be private.

Can we clean the public interface to really keep just the public methods and properties? I suggest moving the private stuff (if any) into an extension in the implementation file and the protected stuff into a separate category header, something like `SRRecorderControl+Subclass.h` (there are some standard Cocoa classes split this way).

I think the change would make the public API more readable. What do you think? I am happy to send a PR.

**Comment by JanX2** [comment]
What happened to this issue? Is the limiting factor time? I could do this.

**Comment by Kentzo** [comment]
@JanX2 Ah I'm not sure that's even needed. My rationale was to have a subclassable UI control and I wanted all methods to be public. For that reason splitting the code into categories is as good as `#pragma mark`.

If you have a different opinion, feel free to share.

**Comment by JanX2** [comment]
It would be nice to have it be immediately obvious, what is necessary and what is optional. I read through the heads and it was too much information to grasp all at once. Better to have something that can be consumed incrementally.

**Comment by Kentzo** [comment]
I have tried to split headers into sections by Task as Apple's docs do.
