### ISSUE TITLE
Review ShortcutRecorder API under Swift

### ISSUE THREAD

**Issue by Kentzo** [Kentzo/ShortcutRecorder#36]
One should test whether current API is usable in Swift applications.

- Rewrite collections to use generics
- Annotate methods with nullability constants
- Annotate designated initializers
- NS_ENUM / NS_OPTIONS
- NS_STRING_ENUM / NS_EXTENSIBLE_STRING_ENUM
- NS_NOESCAPE
- Clang Modules

**Comment by remaerd** [comment]
Hello,

I try to use ShortcutRecorder with Swift 2.1 + Carthage. The Framework was built and Header's looks fine. But no matter how I try, I cannot import the frameworks in Swift. And I have no idea how to solve the problem.

Is there any solution?

**Comment by Kentzo** [comment]
Can you upload a demo project somewhere?

**Comment by remaerd** [comment]
Here you go. I use an Objective-C Framework 'ZipZap' which works.

http://d.pr/f/1aeVh

Thanks.

**Comment by Kentzo** [comment]
Relevant documentation https://developer.apple.com/documentation/swift/objective-c_and_c_code_customization

**Comment by Kentzo** [comment]
3.0 is designed with Swift in mind.
