### ISSUE TITLE
PTHotKey looks for non-existent file PTKeyCodes.plist

### ISSUE THREAD

**Issue by DanielGibbsNZ** [Kentzo/ShortcutRecorder#41]
When calling `description` on a `PTHotKey` object, it tries to load the non-existent file `PTKeyCodes.plist`, which causes an exception with the message `*** -[NSURL initFileURLWithPath:]: nil string parameter`.

Should this file be included in the `PTHotKey` framework or should the code trying to load it be removed?

**Comment by Kentzo** [comment]
@DanielGibbsNZ Sorry it took so long. Please take a look at the `develop` branch.
