### ISSUE TITLE
PTHotkey should send actions via NSApplication so responder chain is used for nil targets

### ISSUE THREAD

**Issue by gotow** [Kentzo/ShortcutRecorder#43]
[PTHotkey invoke] and uninvoke currently call [NSObject performSelector:withObject:] to execute their selector. Calling [NSApplication sendAction:to: from:] would allow the hotkeys to invoke actions on the standard responder chain when the target is nil, adding flexibility and more closely following the standard Cocoa application architecture.

**Comment by Kentzo** [comment]
@gotow PR is welcome :)

**Comment by gotow** [comment]
> On Sep 6, 2015, at 6:12 PM, Ilya Kulakov <notifications@github.com> wrote:
> 
> @gotow PR is welcome :)

I'll definitely be mentioning it in the ReadMe, documentation, etc for Default Folder X 5 when it's released.

 - Jon

**Comment by Kentzo** [comment]
@gotow Oh, I meant Pull Request :p

**Comment by gotow** [comment]
> On Sep 8, 2015, at 11:36 AM, Ilya Kulakov <notifications@github.com> wrote:
> 
> @gotow Oh, I meant Pull Request :p

Haha! My bad. On the way :-)

 - Jon

**Comment by Kentzo** [comment]
Merged.
