### ISSUE TITLE
10.10 - 10.11 "Dark mode" interface style

### ISSUE THREAD

**Issue by su30** [Kentzo/ShortcutRecorder#45]
It is will be very nice if you add "Dark mode" interface style.

**Comment by Kentzo** [comment]
:heavy_dollar_sign:  Complimentary $150 to the author of the best PR ;) :heavy_dollar_sign:

**Comment by Kentzo** [comment]
@su30 Is it for all controls though? Would help if you attach a screenshot of what you expect from that graphics.

Normally, if you design your own UI you design _everything_ :) So defaults here would be rather unhelpful.

**Comment by Kentzo** [comment]
Superseded by #80
