### ISSUE TITLE
Record escape key

### ISSUE THREAD

**Issue by nrbrook** [Kentzo/ShortcutRecorder#46]
Is there a way to record the escape key without a modifier? Thanks

**Comment by Kentzo** [comment]
Certain shortcuts are reserved by system. ShortcutRecorder uses old Carbon method to retrieve all such shortcuts (CopySymbolicHotKeys) and enumerate through them.

If match is found, error is reported.

In other hand, you can always disable this by adopting SRValidatorDelegate and implementing `shortcutValidatorShouldCheckSystemShortcuts`. Or you can subclass SRValidator itself.

**Comment by nrbrook** [comment]
It turns out there is a method to set this on SRRecorderControl, `-setAllowsEscapeToCancelRecording:`, and also `-setAllowsDeleteToClearShortcutAndEndRecording:`, which I was setting to YES and had forgotten about.
