### ISSUE TITLE
Keep SRControlView origin/width

### ISSUE THREAD

**Issue by mischievous** [Kentzo/ShortcutRecorder#52]
I tried the SRControlView in my window but it completely moved the origin of the control to the top of the window which that caused all sorts of other problems.  Is there way way you control view and just stay where it was place in interface builder....  

Thanks,
Alexandra

**Comment by Kentzo** [comment]
Do you mean the SRRecorderControl view?

**Comment by Kentzo** [comment]
The SRRecorderControl internal coordinate system is flipped, however it should not affect parental geometry. Could you upload a screenshot? If you're using auto-layout please check constraints.

The frameworks comes with a demo where among other there is an IB demo. There it works properly.

**Comment by Kentzo** [comment]
@mischievous Please ping me here if you still have this problem.
