### ISSUE TITLE
Update graphics for El Capitan

### ISSUE THREAD

**Issue by Kentzo** [Kentzo/ShortcutRecorder#54]
I offer a complimentary bonus of $100

**Comment by JanX2** [comment]
Are there any source assets for this? 
Working off of the pixels and recreating all the files that way would be cumbersome.

**Comment by Kentzo** [comment]
@JanX2 I want to keep it in the sketch format as it's more accessible to non-devs who usually handle graphics :)

How the update process is usually done: you extract macOS image resources and compare images against shape one of the buttons (don't remember type by heart).

This needs to be reviewed by someone who also has access to various displays (non-retina, retina and 5k).

**Comment by JanX2** [comment]
I have access to all but the 5k display, but I do have ways of simulating that via display buffer scaling technique. 

For more complex graphics, I would agree that the approach using Sketch is necessary. For these relatively simple graphics, it appears to be overkill. Drawing this in code would make the differently-sized pixel-based images unnecessary and allow for handling arbitrary resolutions. Even customization for specific contexts (OS, scale factors, etc.) would become easy.

**Comment by Kentzo** [comment]
Most of the macOS controls are drawn from images, because drawing in code is unnecessary complicated, may produce inaccurate image and the benefits you outlined above may play against you.

This fork has a few commercial customers, for some of them I worked, that I know for sure used Sketch as a basis for customization. I don't want to bring their flow.

**Comment by JanX2** [comment]
Ok. Good arguments. 

I have been using PDFs in my commercial and free apps for years. If you know what you are doing (regarding design) the results are a much better workflow and a greater choice of editing tools. 

Drawing in code can be a chore when things get complex. Like icons. 

What about using PDF images?

**Comment by Kentzo** [comment]
@JanX2 I'm not sure these images can be accurately expressed in vector. The idea is to mimic drawings of native controls *exactly*, pixel to pixel. There is lot with very sharp eye for details :)

**Comment by Kentzo** [comment]
As we're talking about images, I think it worth to note that screenshots also need to be replaced with tiff.

**Comment by JanX2** [comment]
Why use TIFFs for the screenshots?

For such a 1 px line you would have to use drawing in code or separate PDFs. True.

**Comment by Kentzo** [comment]
> Why use TIFFs for the screenshots?

So that screenshots in README won't look blurry on retina displays :)

**Comment by JanX2** [comment]
Do you mean multi-res in a single TIFF file? I would just use a single PNG and scale that down, if necessary.

**Comment by JanX2** [comment]
What is the macOS UI widget you used as a template for the design?

**Comment by JanX2** [comment]
As an aside, the thin Aqua blue border clashes editing state clashes with the graphite focus ring in the Graphite appearance.

**Comment by Kentzo** [comment]
> SRs design is more in-line with the design language of the OS. So I would keep the gray fill the way it is.

If I recall correctly, SR mimics exactly the Bevel button. Basically new images should be created for each platform where new shape was introduced.

> As an aside, the thin Aqua blue border clashes editing state clashes with the graphite focus ring in the Graphite appearance.

Isn't this border part of the image? Each image must have a second version then with proper colors for the Graphite appearance on the affected platforms.

> The also don’t share the very same corner radius resulting in small white gaps

The focus ring shape needs to be tweaked in SRRecorderControl for that platform and image then.

**Comment by Kentzo** [comment]
@JanX2 [`drawFocusRing`](https://github.com/Kentzo/ShortcutRecorder/blob/master/Library/SRRecorderControl.m#L1052-L1056) and [`focusRingMaskBounds`](https://github.com/Kentzo/ShortcutRecorder/blob/master/Library/SRRecorderControl.m#L1058-L1064) methods control how focus ring is drawn, and [`controlShape`](https://github.com/Kentzo/ShortcutRecorder/blob/dba78bc/Library/SRRecorderControl.m#L284-L297) defines the shape focus ring is drawn around.

**Comment by Kentzo** [comment]
@JanX2 Couldn't find the asset for the pressed state and sticked with the Yosemite until 10.13
