### ISSUE TITLE
Crash on OS X 10.11

### ISSUE THREAD

**Issue by anthonycastelli** [Kentzo/ShortcutRecorder#55]
There isn't any crash log or traceback for this issue, but it also happens so randomly too. I can semi-consistently get it to happen if I remove any data my app has stored and try to create a shortcut. All I have to do is click on the field to get it to begin editing and then I get the crash. Here is a screenshot of this issue.

<img width="2302" alt="screen shot 2016-02-12 at 7 23 19 pm" src="https://cloud.githubusercontent.com/assets/2137365/13025522/225343b6-d1be-11e5-8dcd-28b749c34316.png">

**Comment by Kentzo** [comment]
Hi Anthony,

While in debugger, please call `bt` to get backtrace.

Best Regards
Ilya Kulakov

**Comment by Kentzo** [comment]
The problem seems to be delegate got deallocated while SRRecorderControl.

The project does not use the `weak` keyword because of compatibility. However, it should be easy to add this if your project is built against 10.7 and higher.

**Comment by anthonycastelli** [comment]
Here is the backtrace. Thanks for the tip on that one. I had no idea that existed. 

```
(lldb) bt
* thread #1: tid = 0xff596c, 0x00007fff8809eec1 libobjc.A.dylib`objc_retain + 33, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0x40900010020)
    frame #0: 0x00007fff8809eec1 libobjc.A.dylib`objc_retain + 33
  * frame #1: 0x00000001003f99e3 ShortcutRecorder`-[SRRecorderControl beginRecording](self=0x00006000001e3200, _cmd="beginRecording") + 147 at SRRecorderControl.m:229
    frame #2: 0x00000001004011c5 ShortcutRecorder`-[SRRecorderControl mouseUp:](self=0x00006000001e3200, _cmd="mouseUp:", anEvent=0x0000608000123980) + 581 at SRRecorderControl.m:1260
    frame #3: 0x00007fff84e9b067 AppKit`-[NSWindow _handleMouseUpEvent:isDelayedEvent:] + 119
    frame #4: 0x00007fff84e9bfad AppKit`-[NSWindow _reallySendEvent:isDelayedEvent:] + 212
    frame #5: 0x00007fff847f4735 AppKit`-[NSWindow sendEvent:] + 517
    frame #6: 0x00007fff847f0e49 AppKit`-[NSApplication sendEvent:] + 2540
    frame #7: 0x00007fff8472403a AppKit`-[NSApplication run] + 796
    frame #8: 0x00007fff846a6520 AppKit`NSApplicationMain + 1176
    frame #9: 0x0000000100038e57 Lights`main + 87 at AppDelegate.swift:12
    frame #10: 0x00007fff8615c5ad libdyld.dylib`start + 1
(lldb) 
```

**Comment by Kentzo** [comment]
@anthonycastelli I think it would be better if you fix the issue when delegate outlives recorder control. If you need this of some reason, you can manually reset delegate to NULL before it gets deallocated.

**Comment by anthonycastelli** [comment]
@Kentzo Where should all of this happen? In the framework or in my ViewController?

**Comment by Kentzo** [comment]
In your code.

You need to track why delegate is being deallocated before ShortcutRecorder.

**Comment by Kentzo** [comment]
@anthonycastelli I bumped OSX version to 10.7 in the develop branch and update properties. Please take a look.

I'm going to release it after I merge currently open PR.
