### ISSUE TITLE
SRKeyCodeTransformer class doesn't seem to work as expected

### ISSUE THREAD

**Issue by suewonjp** [Kentzo/ShortcutRecorder#56]
Problem:
1. On the demo program, **SRRecorderControl** doesn't show shortcut keys on my system.  
1. Say the shortcut key is **⌘ + A**. It just renders only ⌘. Doesn't display A at all.
   - For whatever shortcut keys, it just shows modifier keys only and ignores character keys.

* * *
With a little bit of debugging, it looks to me that the following method in the class **SRKeyCodeTransformer** is not working correctly.

> **(NSString *)transformedValue:(NSNumber *)aValue withImplicitModifierFlags:(NSNumber *)anImplicitModifierFlags explicitModifierFlags:(NSNumber *)anExplicitModifierFlags**

The method returns a null character @"" for a valid input of @"0", which is a key code **kVK_ANSI_A**

That's because every attempt to call **TISGetInputSourceProperty** API returns nil for some reason.

* * *

My environment is a little bit latest. That is why?

My system:
- Mac mini late 2012
- OS X 10.11.3 (El Capitan)
- Xcode Version 7.2.1 (7C1002)

**Comment by Kentzo** [comment]
This might be related to https://github.com/Kentzo/ShortcutRecorder/issues/48

What is the value of `tisSource`? Is it nil or some valid pointer?

**Comment by Kentzo** [comment]
If `tilSource` is not NULL, could you print the result of `(CFStringRef)TISGetInputSourceProperty(tisSource, kTISPropertyInputSourceType);`?

**Comment by suewonjp** [comment]
> What is the value of tisSource? Is it nil or some valid pointer?

```
(lldb) po tisSource
<TSMInputSource 0x61000002a740> Input Mode: com.apple.inputmethod.Roman (Parent = com.apple.inputmethod.Kotoeri)
```
tisSource is valid but that is all I can get:

> Are you using ASCI capable keyboard input source?

I think so. But I am using multiple input sources (English, Japanese, Korean, Unicode, ...)   
( From the above, **com.apple.inputmethod.Kotoeri** is a Japanese input source object as you may be aware.  )
I guess my environment is a lot similar to the guy at #48 

> Did you mean @0 (NSNumber)?

Yep. I pressed ⌘ + A, so I think @0 represents kVK_ANSI_A( == 0x0)

> If tilSource is not NULL, could you print the result of (CFStringRef)TISGetInputSourceProperty(tisSource, kTISPropertyInputSourceType)?

layoutData	CFDataRef	@"24 bytes"	0x00007fff7d60a6b0

```
(lldb) po layoutData
TISTypeKeyboardInputMode
```

* * *
All LLDB info has been obtained when I placed a breakpoint at line 312 of SRKeyCodeTransformer.m file.

**Comment by suewonjp** [comment]
According to http://lists.apple.com/archives/cocoa-dev/2009/Aug/msg01510.html,  
this problem has been around for quite a long time.

(CFDataRef)TISGetInputSourceProperty(currentKeyboard, kTISPropertyUnicodeKeyLayoutData) returns null for a Japanese keyboard layout. (I'm using one)

Workaround is using TISCopyCurrentKeyboardLayoutInputSource API according to http://stackoverflow.com/questions/1918841/how-to-convert-ascii-character-to-cgkeycode

I tested it like the following. It seems working... 

```
if (self.usesASCIICapableKeyboardInputSource)
    {
        TISInputSourceRef tisSource = TISCopyCurrentASCIICapableKeyboardInputSource();

        if (!tisSource)
            return @"";

        layoutData = (CFDataRef)TISGetInputSourceProperty(tisSource, kTISPropertyUnicodeKeyLayoutData);
        CFRelease(tisSource);
// ************************************************
        if (!layoutData) {
            tisSource = TISCopyCurrentKeyboardLayoutInputSource();
            layoutData = (CFDataRef)TISGetInputSourceProperty(tisSource, kTISPropertyUnicodeKeyLayoutData);
            CFRelease(tisSource);
        }
// ************************************************
    }
    else {...}
```

* * *
**_Another problem:_**

Shortcuts with ⌘ or ⌥ work, but shortcuts with **⌃(control) don't seem to work**. This is by design?

**Comment by Kentzo** [comment]
> self.usesASCIICapableKeyboardInputSource
I.e. this property is set to YES, ok.

> this problem has been around for quite a long time.
@suewonjp I don't think it's a bug actually. That topic is under documented. And names of the constants a little bit misleading. I was somewhat aware of this problem but lack of language specific knowledge didn't allow me to fix it :(

I don't truly understand what input mode is, it seems to be language specific. Could you explain this input concept to me?

**Comment by Kentzo** [comment]
@suewonjp Please try version from the issue-56 branch.

**Comment by suewonjp** [comment]
> I don't truly understand what input mode is, it seems to be language specific. Could you explain this input concept to me?

Well, Japanese input source has several modes 
- Romaij which is a plain English
- Hiragana (one form of Japanese alphabets)
- Katagana (another form of Japanese alphabets)

You can switch between them. (quite inconvenient)

As you mention, one can say it's language specific.

I wanted to say that I just pressed a plain ASCII key code (not a Japanese character)

BTW, is the following code not OK  for every case? (whether Ascii or not)  
(Please, understand that I'm quite new for Cocoa programming. There are much I don't know yet)

```
      tisSource = TISCopyCurrentKeyboardLayoutInputSource();
      layoutData = (CFDataRef)TISGetInputSourceProperty(tisSource, kTISPropertyUnicodeKeyLayoutData);
```

**Comment by Kentzo** [comment]
@suewonjp The difference between ASCI and non-ASCI mode is what character will be printed. In non-ASCI mode the control may print locale and input source dependent character, e.g. `⌘ + Ы`. In ASCI mode it will always print `⌘ + S` despite current input source.

Given that:

- Majority of apps and docs are designed, written and supported in English, 
- Most (all?) keyboards have ASCI layout on top of them

the control defaults to use ASCI representation. But developers are free to change it.

**Comment by Kentzo** [comment]
@suewonjp Please let me know if fix in the issue-56 branch worked for you.

**Comment by suewonjp** [comment]
Thanks. It has got better.

But not perfect. Because it doesn't work like the other universal apps do (e.g., Xcode Key Binding UI) at least on my system.

1. As I asked you before, shortcuts with ⌘ or ⌥ work, but **shortcuts with ⌃(control) don't work**.
    - For example, ⌘A, ⌘⇧A, ⌥A, ⌘⌥A  =>  visible  (O)
    - But, ⌃A   => not visible (X)
1.  Shortcuts with only ⇧ are accepted.
    - For example, when I press ⇧A, your UI happily accepts it.  
    - ⇧A is just a literal A, so it can't be accepted 

I don't know if these two behaviors  are side bugs related to this issue or separate problems or decision by design. Please, let me know.

**Comment by suewonjp** [comment]
Sorry. I checked your demo source and found the following code.

```
[self.pingShortcutRecorder setAllowedModifierFlags:NSShiftKeyMask | NSAlternateKeyMask | NSCommandKeyMask
                                 requiredModifierFlags:0
                              allowsEmptyModifierFlags:NO];
```

That's OK. Your UI is at least configurable in order to fit any convention.

But also it's true that I was a little bit surprised.  

In my humble opinion, I recommend you change NSShiftKeyMask => NSControlKeyMask in the demo source. 

I think there'll be some people like me who is surprised and baffled for a while when your demo accepts a ⇧ and rejects ⌃.

**Comment by Kentzo** [comment]
@suewonjp Yeah, the demo app explicitly limits allowed modifiers to demonstrate the ability. I think it worths to add a label with description, otherwise, as you proved, it may be misleading.
