### ISSUE TITLE
Linking with CocoaPods

### ISSUE THREAD

**Issue by larsblumberg** [Kentzo/ShortcutRecorder#58]
I would prefer using CocoaPods over a git submodule. Did anybody have success in doing so?

When I add a dependency to my `Podfile`

    pod 'ShortcutRecorder', :git => 'https://github.com/Kentzo/ShortcutRecorder.git', :tag => '2.15'

Xcode will spit out this error when running the app that makes use of a `SRRecorderControl ` in its storyboard:

    Failed to set (contentViewController) user defined inspected property on (NSWindow): Unable to find bundle with resources.

Additionally, the control is not displayed in the storyboard. Xcode shows this error here:

    file:///Users/.../shortcutrecorder-demo/Base.lproj/Main.storyboard: error: IB Designables: Failed to render instance of SRRecorderControl: The agent threw an exception.

**Comment by Kentzo** [comment]
@larsblumberg Could you upload a demo project that would demonstrate the issue?

**Comment by Kentzo** [comment]
@larsblumberg Also try http://stackoverflow.com/questions/29933691/ibdesignable-from-external-framework and let me know if it works: I'll update the README.

**Comment by larsblumberg** [comment]
Uploaded a simple project, it just has a CocoaPods dependency to ShortcutRecorder and a  `SRRecorderControl` added to its storyboard: https://github.com/larsblumberg/shortcutrecorder-cocoapods-demo

**Comment by larsblumberg** [comment]
I didn't have success when following the steps from the cited stackoverflow answer. I'm not even sure if I applied the suggestion correctly.

**Comment by Kentzo** [comment]
@larsblumberg Try version from the [issue-58](https://github.com/Kentzo/ShortcutRecorder/tree/issue-58) branch.

**Comment by larsblumberg** [comment]
Branch [issue-58](https://github.com/Kentzo/ShortcutRecorder/tree/issue-58) fixes both issues – the control not appearing at runtime and in the storyboard. Great! Will you merge to master?

PS: Xcode says that there's a `[super dealloc]` missing in `PTKeyCodeTranslator.m` / `(void)dealloc{}`

**Comment by Kentzo** [comment]
Hmm, I don't really support PT these days. I'll see into this issue though.

Overall, I'd suggest to find a modern alternative to register global shortcuts.

**Comment by larsblumberg** [comment]
I personally don't use the PT feature. Xcode had me just pointed to that issue.

**Comment by Kentzo** [comment]
I wonder if it's possible with CocoaPods to opt out this framework from building.

**Comment by Kentzo** [comment]
@larsblumberg Merged and released 2.16

**Comment by larsblumberg** [comment]
@Kentzo Thank you very much!

**Comment by larsblumberg** [comment]
@Kentzo It's possible to opt out PT if you create a Core subspec. By then only specifying `pod 'ShortcutRecorder/Core'` CocoaPods would install the core part w/o PTHotKey.

See here: https://github.com/jverkoey/nimbus/blob/master/Nimbus.podspec and also here: http://stackoverflow.com/questions/20345566/how-do-you-install-a-pods-sub-spec-without-installing-the-whole-pod

**Comment by Kentzo** [comment]
@larsblumberg PR is welcome :)

**Comment by larsblumberg** [comment]
Will prepare a PR

**Comment by larsblumberg** [comment]
https://github.com/Kentzo/ShortcutRecorder/pull/60
