### ISSUE TITLE
Add support for value binding in storyboard

### ISSUE THREAD

**Issue by larsblumberg** [Kentzo/ShortcutRecorder#59]
Is there a reason that `SRRecorderControl` doesn't provide a storyboard property for value binding (apart from nobody did it so far)?

I would like to bind its `objectValue` (NSDictionary) to an object to avoid writing glue code.

**Comment by Kentzo** [comment]
@larsblumberg SRRecorderControl [supports](https://github.com/Kentzo/ShortcutRecorder/blob/master/Library/SRRecorderControl.m#L1403-L1410) the value binding. See [Demo](https://github.com/Kentzo/ShortcutRecorder/blob/master/Demo/IKIBAutoLayoutWindowController.m) for examples.

**Comment by larsblumberg** [comment]
@Kentzo Why it doesn't appear in the storyboard?

**Comment by Kentzo** [comment]
@larsblumberg That's the Q I don't have an answer for.

Does it work for other UI elements added via CocoaPods?

**Comment by larsblumberg** [comment]
At the moment I'm not aware of other Pods providing UI controls with bindings. Will come back to this issue as soon as I find one.

**Comment by Kentzo** [comment]
As far as I can tell, Xcode does not understand bindings exposed from non-standard views.
