### ISSUE TITLE
How to record system wide shortcuts as Cmd+Tab?

### ISSUE THREAD

**Issue by larsblumberg** [Kentzo/ShortcutRecorder#66]
How can I make SRRecorderControl record system wide keyboard shortcuts such as Cmd+Tab or Cmd+Space?

**Comment by Kentzo** [comment]
Mac OS X handles those before it even reaches your app.

**Comment by larsblumberg** [comment]
I thought there would be an OS X API that would allow to temporarily disable system wide shortcut and thus sent to our apps. I had seen another shortcut recorder control that had an extra option that when enabled would allow system keyboard shortcuts such as Cmd+Tab

**Comment by Kentzo** [comment]
@larsblumberg It should be possible to handle Cmd+Tab, e.g. see this stackoverflow [question](http://stackoverflow.com/questions/6215201/catch-system-event-as-cmd-tab-or-spotlight-in-a-cocoa-app).

ShortcutRecorder is just a UI component that tries to avoid any sophisticated interaction with system events. I'd suggest you to implement the necessary bits somewhere in your app where it's the most appropriate. Then simply set new value of the shortcut recorder for rendering.
