### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by Kentzo** [Kentzo/ShortcutRecorder#75]
> "The key combination \"%@\" is already in use."

needs to be translated into:

- [x] Korean 
- [x] Thai
- [x] Simplified Chinese
- [x] Traditional Chinese

Vocabulary reference:

Korean:

    "The key combination \"%@\" can't be used because %@." = "\"%@\" 키 조합은 다음 이유로 사용이 불가능합니다: %@ ";

Thai:

    "The key combination \"%@\" can't be used because %@." = "ใช้คีย์ลัด \"%@\" ไม่ได้ เพราะ %@";

Simplified Chinese:

    "The key combination \"%@\" can't be used because %@." = "无法使用快捷键组合%@，因为%@。";

Traditional Chinese:

    "The key combination \"%@\" can't be used because %@." = "無法使用快捷鍵組合 \"%@\"，因為 %@。";

**Comment by dmitry-moskalets** [comment]
Can help you with Ukrainian translation.

**Comment by Kentzo** [comment]
@dmitry-moskalets New languages are always welcome!

You can use any of the languages listed at https://github.com/Kentzo/ShortcutRecorder/tree/develop/Resources as a reference.

I found 3 locale identifiers related to Ukranian:
1. uk
2. uk_UA
3. ru_UA

I do not know which one macOS prefers when system's language is set to Ukranian though.
