### ISSUE TITLE
Support macOS Mojave dark mode

### ISSUE THREAD

**Issue by nrbrook** [Kentzo/ShortcutRecorder#80]
I'd love to see Mojave support, I need it for my App. I will look in to adding support if I get chance

**Comment by Kentzo** [comment]
Sounds great. Please take a look at the https://github.com/Kentzo/ShortcutRecorder/pull/70 by @JanX2. It has updated assets. However, I'm not sure at this point whether it will be merged as is.

**Comment by nrbrook** [comment]
Thanks, I’ve been working on it today. Do you have any tips on creating the background images - are they copies of existing UI elements? What about the snap back and clear icons?

**Comment by Kentzo** [comment]
The assets of the control are based on the button styled as "Textured Rounded". The clear and snap are system assets as is (at least used to be).

I used https://github.com/insidegui/AssetCatalogTinkerer to extract them originally.

**Comment by nrbrook** [comment]
When are the 'highlighted' images used and what are they based on?

**Comment by Kentzo** [comment]
I think originally they were based on the system assets. Then they were redrawn by @aljungberg and then again by @jwells89 in https://github.com/Kentzo/ShortcutRecorder/pull/33.

The control used to draw different background when mouse pointer was over it. This feature was retained although current assets do not have assets for this state.

**Comment by Kentzo** [comment]
I'm thinking of an abstraction to allow simpler control customization (asset-wise). Do not worry about code.

**Comment by nrbrook** [comment]
Please see https://github.com/Kentzo/ShortcutRecorder/pull/82

Please improve the assets as you see fit

**Comment by Kentzo** [comment]
@jwells89 Is it different than https://github.com/Kentzo/ShortcutRecorder/blob/develop/Resources/ShorcutRecorder%20Yosemite.sketch ?

@nrbrook Would it be possible to provide a sketch file instead?

**Comment by nrbrook** [comment]
@kentzo sorry I’ve not used sketch before and did it directly in photoshop. It’s all done with effects though so is editable/transferable.
Dark mode is included in #82. Includes code to load the appropriate images of the appearance changes, as we can’t do it the automatic way using appearance specific assets as we support older macOS (not sure why Apple didn’t seem to consider this possibility and document alternative methods, but I think what I do in #82 is the way it should be done)

**Comment by aljungberg** [comment]
> If I recall correctly the assets of the control are based on the button styled as "Textured Rounded". The clear and snap are system assets as is (at least used to be).
> 
> I used https://github.com/insidegui/AssetCatalogTinkerer to extract them originally.
> 
> @aljungberg may recall more :)

Yeah I drew them by hand in Photoshop based on UI widgets. It's just some gradients, strokes, a rounded rectangle. I'd probably have used Sketch if I did it today.

**Comment by Kentzo** [comment]
Part of the Shortcut Recorder 3.0
