### ISSUE TITLE
Support for Swift Package Manager

### ISSUE THREAD

**Issue by dempseyatgithub** [Kentzo/ShortcutRecorder#95]
Swift Package Manager packages are integrated into Xcode 11. Now that the Apple toolchain has a supported package manager, it would be great if ShortcutRecorder could be part of that ecosystem.

**Comment by Kentzo** [comment]
That’s in my TODO after I wrap up with 3.0 which should happen quite soon.

PRs are welcome as always

**Comment by Kentzo** [comment]
Apparently SPM still does not support resource bundles: https://bugs.swift.org/browse/SR-2866

**Comment by Kentzo** [comment]
Perhaps other useful code (like actions and monitors) can be bundled in a swift package.

**Comment by Kentzo** [comment]
Swift 5.3 will [include](https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md) support for resource bundles.

**Comment by Kentzo** [comment]
WIP can be found at https://github.com/Kentzo/ShortcutRecorder/tree/spm (subject to force push, do not rely on its revisions).

Current obstacle: https://forums.swift.org/t/undefined-c-symbols-in-pure-objective-c-library-target/37227

**Comment by donly** [comment]
> WIP can be found at https://github.com/Kentzo/ShortcutRecorder/tree/spm (subject to force push, do not rely on its revisions).
> 
> Current obstacle: https://forums.swift.org/t/undefined-c-symbols-in-pure-objective-c-library-target/37227

I have a try to use this in Xcode 12 beta 3, while compiling it shows these errors.
`/SourcePackages/checkouts/ShortcutRecorder/Sources/ShortcutRecorder/SRCommon.m:42:33: error: expected ';' after return statement
    return SWIFTPM_MODULE_BUNDLE
                                ^
                                ;`

**Comment by Kentzo** [comment]
@donly Changes from the spm branch were merged into the develop branch. I have fixed that bug there. Please let me know how it goes.

**Comment by donly** [comment]
After adding `https://github.com/Kentzo/ShortcutRecorder.git` to Swift Packages with `develop`, there are three issues.

```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/donly/Library/Developer/Xcode/DerivedData/ScreenJumper-crsejavorpbkdteidzxlnwvjekqm/SourcePackages/checkouts/ShortcutRecorder/Sources/ShortcutRecorder/include/ShortcutRecorder/ShortcutRecorder.h"
        ^
/Users/donly/Library/Developer/Xcode/DerivedData/ScreenJumper-crsejavorpbkdteidzxlnwvjekqm/SourcePackages/checkouts/ShortcutRecorder/Sources/ShortcutRecorder/include/ShortcutRecorder/ShortcutRecorder.h:6:9: error: 'ShortcutRecorder/SRCommon.h' file not found
#import <ShortcutRecorder/SRCommon.h>
        ^
/Users/donly/Documents/project/screen-jumper/ScreenJumper/widget/ScreenList.swift:10:8: error: could not build Objective-C module 'ShortcutRecorder'
import ShortcutRecorder
```

**Comment by Kentzo** [comment]
Could you attach the compilation log?

Best Regards
Ilya Kulakov

**Comment by donly** [comment]
The project is open source, please see https://github.com/donly/screen-jumper/tree/spm. 

Thanks a lot, Kentzo

**Comment by Kentzo** [comment]
Hmm, I do not see Package definition there.

**Comment by Kentzo** [comment]
Found and fixed the issue, please try again.

**Comment by donly** [comment]
Awesome, it works very well.
Thanks.

**Comment by daveverwer** [comment]
I see that the `spm` branch has been merged in, and the readme file says that SPM is supported. That's great news! Unfortunately, I am having a problem, related to the `@IBDesignable` code in the package.

I added the package and everything builds fine, but as soon as I add a `SRRecorderControl` to a storyboard I get an error as it tries to build for Interface Builder. The app itself runs and works, but every time IB tries to refresh the views the error shows up.

```
SRCommon.h:6:9: Cocoa is not available when building for tvOS Simulator. Consider using `#if !TARGET_OS_TV` to conditionally import this framework, first importing TargetConditionals.h if necessary.
```

The most confusing thing about this error message is that this is a macOS app, with no tvOS (or any iOS based) targets at all.

Naturally, adding a `RecorderControl` in code works great, and that's the approach I'm using for now.

I thought I'd mention it though, and see if anyone else has a better workaround than creating it in code. Let me know if you'd rather I open this as a separate issue, I'd be happy to.

**Comment by Kentzo** [comment]
Interesting, what version of Xcode are you trying that in?

**Comment by daveverwer** [comment]
Apologies, I should have included that! I'm running the latest stable, Version 12.2 (12B45b) on Big Sur.

I just made a new project, imported the package and placed a view on the view controller in the storyboard and reproduced it. [Here's the project](https://github.com/Kentzo/ShortcutRecorder/files/5611754/Test.zip).
