### ISSUE TITLE
Documentation and examples not clear on how to register a global shortcut

### ISSUE THREAD

**Issue by dempseyatgithub** [Kentzo/ShortcutRecorder#97]
I was updating a project that used the pre-10.6, 32-bit version of ShortcutRecorder. Thank you so much for this new version - with macOS Catalina the project absolutely needs to get off of the 32-bit only version!

It was relatively easy to move to the new APIs by reading the documentation in the headers and looking at the playground.

One thing I am stumped by is how to register the shortcuts as a global shortcut.

That could use better documentation of some kind.

Are `+[SRShortcutRegistration enableShortcutRegistrations]` and `+[SRShortcutRegistration disableShortcutRegistrations]` what should be used?

And if so, do I use them on app launch and app termination?

Or am I on the wrong track completely?

(Once I have the answer, I'd also be happy to add to the header documentation and submit a PR with the changes.)

**Comment by Kentzo** [comment]
`enableShortcutRegistrations` / `disableShortcutRegistrations` control whether underlying Carbon hot keys are active. This is used by SRRecorderControl to suppress all registrations during recording.

Consider the following use-case: you have a control whose value is bound to a shortcut registration. A user begins recording and types exactly the same shortcut. Without suppression, you'd either get an error from an instance of SRValidator or you'd trigger the shortcut.

**Comment by Kentzo** [comment]
I redid the API and the docs regarding global shortcut registrations.

Regarding the question specifically, the enable/disable terminology was substituted with resume/pause. The docs explicitly point out that `SRGlobalShortcutMonitor` is resumed by default.
